### ISSUE TITLE
VSCode remote debugging error - debugger dies (this reference)

### ISSUE THREAD

**Issue by afust003** [Krzysztofz01/AccessPointMap#5]
Hi,  cloned the repo and had to make a series of changes to get the front-end (client app) to compile.
Note: I can provide details if need be.

Question: what is the "debug" workflow/process you are using for the front-end app?
I'm getting the following error when I try to debug the angular app through VS code:

Error:
/usr/share/nginx/html # node --inspect-brk=0.0.0.0:9229 main.js
Debugger listening on ws://0.0.0.0:9229/c10c49bc-2c46-47ee-80cb-97c20c7a52bb
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
/usr/share/nginx/html/main.js:1
(self["webpackChunkaccess_point_map"] = self["webpackChunkaccess_point_map"] || []).push([["main"],{
^

ReferenceError: self is not defined
    at Object.<anonymous> (/usr/share/nginx/html/main.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1082:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

A few observations:
1. no webpack.config that I can see
2. had to extensively change DockerFile (see below) so that I could use 1 image that contains 'node' v14 installed so that we could remote debug once app is deployed inside container....
// -- DockerFile code -- //
FROM hoosin/alpine-nginx-nodejs AS build
#see-> https://github.com/hoosin/alpine-nginx-nodejs
#OLD: FROM node:14 AS build
WORKDIR /usr/src/app
COPY . .
COPY package.json package-lock.json ./
RUN npm install
# RUN npm run ng build -- --prod --base-href /projects/accesspointmap/ --deploy-url /projects/accesspointmap/
#RUN npm run ng build -- --prod
RUN npm run ng build
COPY nginx.conf /etc/nginx/nginx.conf
#OLD: COPY --from=build /usr/src/app/dist/AccessPointMap /usr/share/nginx/html
#NEW: within the same image
#See: https://askubuntu.com/questions/86822/how-can-i-copy-the-contents-of-a-folder-to-another-folder-in-a-different-directo
RUN cp -a /usr/src/app/dist/AccessPointMap/. /usr/share/nginx/html/
WORKDIR /usr/share/nginx/html/
EXPOSE 9229

**Comment by Krzysztofz01** [comment]
Hi,
the workflow is done in such a way that the debugging process is carried out locally. After solving a given problem, the application is packed to a container and the tests are repeated. If they don't show up, everything is fine, if they still show up, we go back to work locally. To debug i use a generic chrome debugger extension for VSCode. 

I see you mentioned this line:
`RUN npm run ng build -- --prod --base-href /projects/accesspointmap/ --deploy-url /projects/accesspointmap/`
This line is building the angular app to work on the paths specified by the reverse proxy that the AccessPointMap project used a while ago. Now the ng build command in the dockerfile is configured to work in a environment dedicated only for AccessPointMap containers.

If you want to know more details or have any questions about the project, you can contact me by email.
